<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
const state=ref<any>(null),error=ref(''),busy=ref(false),authUrl=ref(''),search=ref(''),privacyFilter=ref(''),groupFilter=ref('');
const videos=ref(new Set<string>()),artifacts=ref(new Set<string>()),preview=ref<any>(null);
const edit=ref({find:'',replace:'',regex:false,prefix:'',description:'',tags:'',privacy:'',group:''});
const changeDescription=ref(false),changeTags=ref(false),changeGroup=ref(false);
const upload=ref({title:'{文件名}',description:'',tags:'',privacy:'private',category_id:'22',made_for_kids:'no'});
let timer:ReturnType<typeof setInterval>|undefined;
async function api(path:string,body?:any){const r=await fetch('/api/youtube'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error??'请求失败');return v;}
async function load(){state.value=await api('');}
async function run(f:()=>Promise<void>){busy.value=true;error.value='';try{await f();}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function config(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f)await run(async()=>{await api('/config',JSON.parse(await f.text()));await load();});(e.target as HTMLInputElement).value='';}
function toggle(which:string,id:string){const set=which==='videos'?videos:artifacts;const n=new Set(set.value);n.has(id)?n.delete(id):n.add(id);set.value=n;}
const filtered=computed(()=> (state.value?.videos??[]).filter((v:any)=>(!search.value||`${v.snippet.title} ${v.id}`.toLowerCase().includes(search.value.toLowerCase()))&&(!privacyFilter.value||v.status.privacyStatus===privacyFilter.value)&&(!groupFilter.value||v.local_group===groupFilter.value)));
const groups=computed(()=>[...new Set<string>((state.value?.videos??[]).map((v:any)=>v.local_group).filter(Boolean))]);
const available=computed(()=>(state.value?.artifacts??[]).filter((a:any)=>!(state.value?.uploads??[]).some((j:any)=>j.artifact_id===a.output_id&&j.channel_id===state.value?.channel?.id)));
function selectAll(){videos.value=new Set(filtered.value.map((v:any)=>v.id));}
function splitTags(t:string){return t.split(/[,，]/).map(t=>t.trim()).filter(Boolean);}
function makePreview(){run(async()=>{preview.value=await api('/batches/preview',{ids:[...videos.value],find:edit.value.find,replace:edit.value.replace,regex:edit.value.regex,prefix:edit.value.prefix,description:changeDescription.value?edit.value.description:null,tags:changeTags.value?splitTags(edit.value.tags):null,privacy:edit.value.privacy||null,group:changeGroup.value?edit.value.group:null});});}
watch([edit,changeDescription,changeTags,changeGroup,videos],()=>preview.value=null,{deep:true});
onMounted(()=>{run(load);timer=setInterval(()=>{if(!busy.value)load().catch(()=>{});},3000);});onUnmounted(()=>clearInterval(timer));
const labels:Record<string,string>={queued:'排队中',running:'上传中',paused:'已暂停',interrupted:'已中断',failed:'失败',completed:'已完成',pending:'待应用',private:'私密',unlisted:'不公开',public:'公开'};
</script>
<template>
<div class="page-heading"><div><div class="eyebrow">YOUTUBE WORKSPACE</div><h1>成品发布与频道管理<span class="heading-dot">.</span></h1><p>批量选择 → 预览变更 → 提交；上传默认私密，支持暂停和继续。</p></div><button class="subtle" :disabled="busy" @click="run(load)">刷新状态</button></div>
<div v-if="error" class="warning-panel" role="alert">{{error}}</div>
<template v-if="state">
<section class="panel yt-section"><div class="yt-row"><h2>{{state.connected?'已连接：'+(state.channel?.snippet?.title??'频道'):'连接你的 YouTube 频道'}}</h2><span class="badge" :class="state.connected?'green':'neutral'">{{state.connected?'已授权':state.configured?'配置已保存':'需要 OAuth 配置'}}</span></div><p>在 Google Cloud 启用 YouTube Data API v3，创建「桌面应用」OAuth 客户端，导入下载的 JSON。授权信息保存在系统凭据存储中。</p><div class="yt-row"><label class="subtle">导入 OAuth JSON<input type="file" accept=".json" :disabled="busy" @change="config"/></label><button class="primary" :disabled="busy||!state.configured" @click="run(async()=>{authUrl=(await api('/connect',{})).url;})">打开系统浏览器授权</button><a v-if="authUrl" :href="authUrl" target="_blank" rel="noreferrer" class="subtle">备用授权链接 ↗</a><button v-if="state.connected" class="subtle" :disabled="busy" @click="run(async()=>{await api('/disconnect',{});authUrl='';await load();})">断开并撤销授权</button></div><p class="muted">授权后回到此页即可。未通过 YouTube 审核的 API 项目可能被限制为私密上传。</p></section>
<section class="panel yt-section"><div class="yt-row"><h2>上传管线</h2><span class="muted">合并 / 切割成品 → 串行上传队列 → YouTube 处理</span></div><p v-if="!available.length">暂无待上传成品。先在后处理管线执行合并或自动切割。</p><div class="yt-scroll"><label v-for="a in available" :key="a.output_id" class="checkbox-label"><input type="checkbox" :checked="artifacts.has(a.output_id)" @change="toggle('artifacts',a.output_id)"/><span>{{a.path.split(/[\\/]/).pop()}} · {{(a.bytes/1048576).toFixed(1)}} MiB</span></label></div><div class="yt-form"><label class="field-label">标题模板（支持 {文件名}）<input v-model="upload.title"/></label><label class="field-label">公开状态<select v-model="upload.privacy"><option value="private">私密</option><option value="unlisted">不公开</option><option value="public">公开</option></select></label><label class="field-label">标签（逗号分隔）<input v-model="upload.tags"/></label><label class="field-label">分类 ID<input v-model="upload.category_id"/></label><label class="field-label">是否专为儿童制作<select v-model="upload.made_for_kids"><option value="no">否</option><option value="yes">是</option></select></label></div><label class="field-label">描述<textarea v-model="upload.description" rows="3"/></label><button class="primary" :disabled="busy||!state.connected||!artifacts.size" @click="run(async()=>{await api('/uploads',{artifact_ids:[...artifacts],metadata:{...upload,tags:splitTags(upload.tags),made_for_kids:upload.made_for_kids==='yes'}});artifacts=new Set();await load();})">以{{labels[upload.privacy]}}上传 {{artifacts.size}} 个成品</button>
<article v-for="j in state.uploads" :key="j.id" class="yt-job"><div class="yt-row"><strong>{{j.title}}</strong><span class="badge neutral">{{labels[j.status]??j.status}}</span><span>{{labels[j.privacy]}}</span><button v-if="['queued','running'].includes(j.status)" class="subtle" @click="run(async()=>{await api(`/uploads/${j.id}/pause`,{});await load();})">暂停</button><button v-else-if="j.status!=='completed'" class="subtle" :disabled="busy||!state.connected" @click="run(async()=>{await api(`/uploads/${j.id}/resume`,{});await load();})">继续原任务</button><a v-if="j.video_id" :href="'https://www.youtube.com/watch?v='+encodeURIComponent(j.video_id)" target="_blank" rel="noreferrer">查看视频 ↗</a></div><progress :value="j.offset" :max="j.bytes"/><small>{{j.message}}</small></article></section>
<section class="panel yt-section"><div class="yt-row"><h2>频道视频 · {{state.videos.length}}</h2><button class="subtle" :disabled="busy||!state.connected" @click="run(async()=>{await api('/sync',{});await load();})">同步全部频道视频</button></div><div class="yt-row"><input v-model="search" placeholder="搜索标题 / 视频 ID"/><select v-model="privacyFilter"><option value="">全部公开状态</option><option value="private">私密</option><option value="unlisted">不公开</option><option value="public">公开</option></select><select v-model="groupFilter"><option value="">全部本地分组</option><option v-for="g in groups" :key="g">{{g}}</option></select><button class="subtle" @click="selectAll">全选筛选结果</button><button class="subtle" @click="videos=new Set()">清空选择</button></div><div class="yt-scroll"><table><thead><tr><th></th><th>视频标题</th><th>公开状态</th><th>本地分组</th><th>处理状态</th></tr></thead><tbody><tr v-for="v in filtered" :key="v.id"><td><input type="checkbox" :checked="videos.has(v.id)" :aria-label="'选择视频 '+v.snippet.title" @change="toggle('videos',v.id)"/></td><td><a :href="'https://www.youtube.com/watch?v='+encodeURIComponent(v.id)" target="_blank" rel="noreferrer">{{v.snippet.title}}</a><small class="block muted">{{v.id}}</small></td><td>{{labels[v.status.privacyStatus]}}</td><td>{{v.local_group||'未分组'}}</td><td>{{v.status.uploadStatus}}</td></tr></tbody></table></div><p v-if="!state.videos.length" class="muted">连接账号后点击同步，读取频道上传列表（包含自己可管理的私密视频）。</p>
<h3>批量修改 {{videos.size}} 个视频</h3><div class="yt-form"><label class="field-label">标题前缀<input v-model="edit.prefix"/></label><label class="field-label">标题查找<input v-model="edit.find"/></label><label class="field-label">替换为<input v-model="edit.replace"/></label><label class="field-label">公开状态<select v-model="edit.privacy"><option value="">保持原值</option><option value="private">私密</option><option value="unlisted">不公开</option><option value="public">公开</option></select></label></div><label class="checkbox-label"><input type="checkbox" v-model="edit.regex"/>查找使用正则表达式，捕获组替换用 $1</label><div class="yt-form"><label class="field-label"><span><input type="checkbox" v-model="changeTags"/> 替换标签</span><input v-model="edit.tags" :disabled="!changeTags" placeholder="逗号分隔；勾选后留空会清空"/></label><label class="field-label"><span><input type="checkbox" v-model="changeGroup"/> 本地分组</span><input v-model="edit.group" :disabled="!changeGroup" placeholder="应用内分组，不创建 YouTube 播放列表"/></label></div><label class="field-label"><span><input type="checkbox" v-model="changeDescription"/> 替换描述（勾选后留空会清空）</span><textarea v-model="edit.description" :disabled="!changeDescription" rows="3"/></label><button class="subtle" :disabled="busy||!videos.size||!state.connected" @click="makePreview">预览修改</button>
<div v-if="preview" class="yt-preview"><h3>预览 · 确认后写入 YouTube</h3><article v-for="c in preview.changes" :key="c.id"><strong>{{c.before.snippet.title}}</strong><p v-if="c.after.snippet">新标题：{{c.after.snippet.title}}<br/>新描述：{{c.after.snippet.description}}<br/>新标签：{{c.after.snippet.tags?.join(', ')}}</p><p v-if="c.after.status">公开状态：{{labels[c.before.status.privacyStatus]}} → {{labels[c.after.status.privacyStatus]}}</p><p v-if="c.after.local_group!==undefined">本地分组：{{c.after.local_group||'清空'}}</p><small>{{labels[c.status]}} {{c.message}}</small></article><button class="primary" :disabled="busy||!preview.changes.some((c:any)=>c.status==='pending')" @click="run(async()=>{preview=await api(`/batches/${preview.id}/apply`,{});await load();})">确认应用 {{preview.changes.length}} 项修改</button></div>
<details v-if="state.batches.length"><summary>历史批量操作（{{state.batches.length}}）</summary><article v-for="b in state.batches" :key="b.id" class="yt-job"><button class="subtle" @click="preview=b">查看 {{b.id.slice(0,8)}} · {{b.changes.length}} 项</button><span v-for="c in b.changes" :key="c.id">{{labels[c.status]}} </span></article></details></section>
</template>
</template>
<style scoped>
.yt-section{padding:24px;margin-bottom:22px}.yt-row{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:12px 0}.yt-row h2{margin-right:auto}.yt-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px}.yt-scroll{max-height:420px;overflow:auto;margin:16px 0}.yt-job{padding:14px 0;border-top:1px solid #e6ebe8;margin-top:14px}.yt-job progress{width:100%}.yt-section textarea{width:100%;border:1px solid #dce3dd;border-radius:8px;padding:10px;font:inherit}.yt-section input:not([type=checkbox]):not([type=file]),.yt-section select{min-width:140px;max-width:100%;padding:10px;border:1px solid #dce3dd;border-radius:8px}.yt-preview{margin-top:20px;padding:18px;background:#f4f8f5;border:1px solid #dce3dd;border-radius:12px}.yt-preview article{padding:12px 0;border-bottom:1px solid #dce3dd;overflow-wrap:anywhere}.yt-section p{line-height:1.65}.yt-section a{color:#28754e}.yt-section input[type=file]{max-width:240px}table{width:100%}
</style>
